# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d09b6f598b779a49ef8b0840cce053ed57d01af39a86ead18f2ec207de01610b6e97ae5531b3ca1db3da448a7dd9daa4aa10c19a6d9eda33045faaed5bd63814

test:
  secret_key_base: 1037392e304a99c73001b0fb04ea4874183bed42666c9f07b19c810da75b6d751525265d80e92809af3ae1cf2bbefdf97b379829d367686552e77cf879e2dd42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
